# Practice for Join Statements with SQL

Import the necessary packages and connect to the database 'data.sqlite'.

In [15]:
# Run without change

# Libraries and database

import sqlite3
import pandas as pd

conn = sqlite3.connect('data.sqlite')

1. Select the names (frist and last) of all employees in Boston

In [16]:
# Your code here
q = """
SELECT firstName, lastName
	FROM employees
JOIN offices
USING(officeCode)
WHERE city = "Boston";
"""
pd.read_sql(q, conn)

  firstName   lastName
0     Julie   Firrelli
1     Steve  Patterson

2. Are there any offices that have zero employees?

In [17]:
# Your code here
q = """
SELECT
	o.officeCode,
	o.city,
	COUNT(e.employeeNumber) AS employeesCount
FROM offices AS o
LEFT JOIN employees AS e
	USING(officeCode)
GROUP BY officeCode
HAVING employeesCount = 0;
"""
pd.read_sql(q, conn)

   officeCode    city  employeesCount
0          27  Boston               0

3. How many customers are there per office?

In [18]:
# Your code here
q = """
SELECT
    o.officeCode,
    o.city,
    COUNT(c.customerNumber) AS customersCount
FROM offices AS o
JOIN employees AS e
    USING(officeCode)
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
GROUP BY officeCode
;
"""
pd.read_sql(q, conn)

   officeCode           city  customersCount
0           1  San Francisco              12
1           2         Boston              12
2           3            NYC              15
3           4          Paris              29
4           5          Tokyo               5
5           6         Sydney              10
6           7         London              17

4. Display the names of every individual product that each employee has sold as a dataframe.

In [19]:
# Your code here
q = """
SELECT firstName, lastName, productName
FROM employees AS e
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
JOIN products
    USING(productCode);
"""
df = pd.read_sql(q, conn)
df.head(10)

  firstName  lastName                                  productName
0    Leslie  Jennings                               1958 Setra Bus
1    Leslie  Jennings                       1940 Ford Pickup Truck
2    Leslie  Jennings                      1939 Cadillac Limousine
3    Leslie  Jennings  1996 Peterbilt 379 Stake Bed with Outrigger
4    Leslie  Jennings                            1968 Ford Mustang
5    Leslie  Jennings                           1968 Dodge Charger
6    Leslie  Jennings                      1970 Plymouth Hemi Cuda
7    Leslie  Jennings                           1969 Dodge Charger
8    Leslie  Jennings                  1948 Porsche 356-A Roadster
9    Leslie  Jennings                         1969 Dodge Super Bee

5. Display the number of products each employee has sold
- Alphabetize the results by employee last name.
- Use the quantityOrdered column from orderDetails.
- Think about how to group the data when some employees might have the same first or last name.

In [20]:
# Your code here
q = """
SELECT firstName, lastName, SUM(quantityOrdered) as total_products_sold
FROM employees AS e
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
GROUP BY firstName, lastName
ORDER BY lastName;
"""
pd.read_sql(q, conn)

   firstName   lastName  total_products_sold
0       Loui     Bondur                 6186
1      Larry       Bott                 8205
2     Pamela   Castillo                 9290
3      Julie   Firrelli                 4227
4       Andy     Fixter                 6246
5     Martin     Gerard                 4180
6     Gerard  Hernandez                14231
7     Leslie   Jennings                11854
8      Barry      Jones                 7486
9      Peter      Marsh                 6632
10      Mami      Nishi                 4923
11     Steve  Patterson                 5561
12    Leslie   Thompson                 4056
13  Foon Yue      Tseng                 5016
14    George     Vanauf                 7423

6.  Display the names of employees who have sold more than 200 different products.

In [21]:
# Your codde here
q = """
SELECT firstName, lastName, COUNT(productCode) as different_products_sold
FROM employees AS e
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
GROUP BY firstName, lastName
HAVING different_products_sold > 200
ORDER BY lastName;
"""
pd.read_sql(q, conn)

  firstName   lastName  different_products_sold
0     Larry       Bott                      236
1    Pamela   Castillo                      272
2    Gerard  Hernandez                      396
3    Leslie   Jennings                      331
4     Barry      Jones                      220
5    George     Vanauf                      211

In [22]:
conn.close()